### ISSUE TITLE
web page not working

### ISSUE THREAD

**Issue by ashi0077** [PuneethReddyHC/online-shopping-system-advanced#2]
its showing this 

Warning: mysqli_connect(): (HY000/1044): Access denied for user ''@'localhost' to database 'ecommerece' in C:\xampp\htdocs\online-shopping-system-advanced-master\db.php on line 9
Connection failed: Access denied for user ''@'localhost' to database 'ecommerece'

**Comment by PuneethReddyHC** [comment]
Change the variables $username and $db to what you provided during creating and importing sql.
